Not used. = {
Nevyužito.
}

Settings = {
Nastavení
}

Category Mapping Tool = {
Mapování kategorií
}

Logs = {
Logy
}

Help = {
Nápověda
}

Configuration for = {
Konfigurace
}

Supplier's category = {
Kategorie dodavatele
}

Store category = {
Kategorie obchodu
}

All settings changes are message = {
Veškeré změny v nastavení jsou provedeny po spuštění importního modulu =
}

Intro = {
<style>
.highlight {background: #ea9550 ; text-decoration:none;font-size:16px !important;
	;color: #fff !important;padding: 0 4px; -webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px;}
.highlight2 {background: #95ea50 !important;}
.highlight3 {background: #9550ea !important;}
#infobox p {padding:5px;padding-left:15px; }
#infobox, #infobox li, #infobox b, #infobox p {font-family: 'Verdana',monospace,sans-serif;font-size:12px}

</style>
}

AdministrationInterface = <h2 id='admin_interface' class='highlight' style='font-size:22px !important;'>Administrační rozhraní modulu</h2>
CategoryMappingToolInfo = {
 	   <h3 style='padding-left:9px;font-size:16px;text-decoration:underline'>Mapování kategorií</h3>


	        <p>Umožňuje základní nastavení mapování kategorií z Datafeedu dodavatele do vašeho internetového obchodu – lze tedy nastavit do jakých kategorií se zboží bude ukládat. <br />
V pravé části tabulky přiřadíte kategorii Vašeho obchodu do které se nahrají produkty kategorie dodavatele (ty jsou na levé straně).<br />
Samozřejmě je možné do jedné kategorie v eshopu namapovat dvě a více kategorie dodavatele. Lze to i naopak.<br>
Co se týče stromové struktury Vašeho eshopu, je potřeba ji vytvořit předem v administraci obchodu a nebo můžete mít stejnou strukturu kategorií jako dodavatel.<br>
            <Br>
Jen produkty, které jsou v namapovaných kategoriích jsou importovany. Produkty, které jsou již naimportovány a jejich kategorie byla odmapována jsou deaktivovány.

    <br>

}
ImportModuleActivity = {
         <h2 id='sync_script' class='highlight highlight2' style='font-size:22px !important'>Synchronizace = spuštění modulu</h2> <br>

        <p>Můžete spouštět importní modul následovně:
       </p>

        <ul>
        <li>a) manuálně - přes webový prohlížeč. Vložíte URL skriptu do adresního řádku prohlížeče a načtete stránku. </li>
        <li>a) automaticky - přes CRON, který si nastavíte na hostingu či vašem serveru. Příkaz může být např. "wget URL_IMPORTNIHO_SKRIPTU"</li>
         </ul>
        <p>
		Pro oba způsoby platí, že v ten moment se provede vložení nových produktů, aktualizace stávajících produktu či deaktivace produktů. Vše dle nastavení modulu.
		<Br>
		URL adresa skriptu je v zahlaví této stránky.
        </p>
               <br> <br>
	     <h2 class='highlight highlight3' style='font-size:22px !important; '>Logy</h2>    <br>
	     <p>Administrační rozhraní obsahuje sekci Logy, kde je možné sledovat statistiky nově importovaných, aktualizovaných, deaktivovaných položek apod.</p><br>


}
SettingsToolInfo = {
         <h3 id='logsinfo' style='padding-left:9px;font-size:16px;text-decoration:underline'>Nastavení</h3>
         <p>Tato sekce obsahuje další doplňková nastavení modulu.</p>
         <p>Dle vašich požadavků budou přidány další možnosti nastavení modulu.</p><br>
}