Settings = {
Settings
}

Category Mapping Tool = {
Category Mapping Tool
}

Logs = {
Logs
}

Help = {
Help
}

Not used. = {
Not used. We can add any settings according to your requirements. For example :    <br> <br>
  <ul>
  <li>Not synced products price</li>
    <li>Don't update price for following SKU</li>
    <li>Don't update Description for following SKU</li>
    <li>Rules for Generating Product Title</li>
    <li>Profit Margins per price ranges</li>
    <li>Global margin profit</li>
    <li>Discount per manufacturer</li>
    <li>Disable/Don't update following products </li>
    </ul>
}

Configuration for = {
Configuration for
}

Supplier's category = {
Supplier's category
}

Store category = {
Store category
}

All settings changes are message = {
All settings changes are applied after the sync script is launched manually =
}

Intro = {
<style>
.highlight {background: #ea9550 ; text-decoration:none;font-size:16px !important;
	;color: #fff !important;padding: 0 4px; -webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px;}
.highlight2 {background: #95ea50 !important;}
.highlight3 {background: #9550ea !important;}
#infobox p {padding:5px;padding-left:15px; }
#infobox, #infobox li, #infobox b, #infobox p {font-family: 'Verdana',monospace,sans-serif;font-size:12px}

</style>
<p style="font-size:14px;">
eSync Import Module does bulk updates and the synchronization of products between the supplier (wholesaler, dealer) and your online store any time you want. </p>
<p style="font-size:14px;"><b style="font-size:14px;">Import Module Extension</b> is controlled by administration interface which enables you to change the configuration for import process.  </p>

<br>
Help for: <a class='highlight' href='#admin_interface' style='font-size:16px'>Import Module Administration</a>
 | <a  class='highlight highlight2' href='#sync_script' style='font-size:16px'>Import Module Synchronization Script</a>
 | <a  class='highlight highlight3' href='#logsinfo' style='font-size:16px'>Import Module Logs</a>
 <br>
 <br><hr>
}

AdministrationInterface = <h2 id='admin_interface' class='highlight' style='font-size:22px !important;'>Administration Interface - Configuration</h2>
CategoryMappingToolInfo = {
 	   <h3 style='padding-left:9px;font-size:16px;text-decoration:underline'>Category Mapping Tool</h3>


	        <p>Category Mapping Tool consists mainly of two tables. You can associate the <b>suppliers categories</b> to your own store categories. The table on the left contains your supplier’s categories (from Datafeed), the table on the right contains your store categories.
	        <br> In order to import products, you need to create mappings (relation) between these two tables. You can do so by clicking on   <br>
	          <br>
	        <b>You can do it by two ways:</b>

	        </p>
	        <ul class="infoboxlist">
	            <li><b>automated - copy the categories</b> with suppliers category tree - you can click to the Copy green/white arrow icon - it creates category with the same name (firstly root category level and followingly the subcategories) </li>
	            <li><b>manually</b>- select the destination category (= store category) from the select box (you have to create the category tree in your store administration in advance)   </li>
			</ul>
			<p>If you want to place the supplier's category more than once to your store - use the red/white Icon to add another destination for the supplier's category</p>
	        <p>  You can set <b>Margin Profit</b> for each category via input field with "%". For example : Supplier price: 12,50 €, You set the Margin: 20%  => Your price = 15 €
	         </p>
	        <p>Only products linked to the mapped category are synchronized (inserted or updated).</p>
	        <p>Changes in this settings are appeared <b>after the sync script is launched</b> (by CRON or manually way) - the details are sent with email.</p>
            <br>

}
ImportModuleActivity = {
         <h2 id='sync_script' class='highlight highlight2' style='font-size:22px !important'>Import Module Synchronization Script</h2> <br>

        <p>You can run the Import Module inside your internet browser after you entry a specified <b>URL link</b>. This URL link we will send you to your email to avoid the security issues.
        </p>
		<ul class="infoboxlist">
		<li>Automated download of supplier product datafeed file. </li>
		<li>Automated upload of product details from the Data Feed or IceCat Catalog– product price, product name, product description, product upc, category, quantity, images, manufacturer, cross-sells, related products. </li>
		<li>Syncronization of products with your distributor inventory at the time you want (CRON task manager, cPanel)</li>
		</ul>
		<br>

	     <h2 class='highlight highlight3' style='font-size:22px !important; '>Import Module Logs</h2>
	     <p>It enables to you see all import module activities. You can find the logs in the Import Module Administration tab called "Logs"</p><br>


}
SettingsToolInfo = {
         <h3 id='logsinfo' style='padding-left:9px;font-size:16px;text-decoration:underline'>Settings</h3>
         <p>You can find the Setting boxes in the Settings Tab. Each of them has specific function - "Profit Margins per price ranges", "Not synced products per price ranges",
          "Not synced products" etc.</p>
         <p>According to your requirements we are able to add another Settings boxes.</p><br>
}