import { redirect } from 'next/navigation';
import { isAdminAuthenticated } from '../auth';
import { queryNeon } from '../../../lib/neon-client';

export const dynamic = 'force-dynamic';

type RawAttributeRow = { key: string; products: string; examples: string[] };
type CanonicalAttributeRow = { id: string; source_attribute_code: string | null; name: string; data_type: string; is_filterable: boolean; products: string };

export default async function AdminAttributesPage() {
  if (!(await isAdminAuthenticated())) redirect('/admin');
  const [stats, rawRows, canonicalRows] = await Promise.all([
    queryNeon<{ products: string; with_attributes: string; average: string; maximum: string }>(`SELECT COUNT(*)::text AS products, COUNT(*) FILTER (WHERE attributes <> '{}'::jsonb)::text AS with_attributes, ROUND(AVG((SELECT COUNT(*) FROM jsonb_object_keys(attributes))), 2)::text AS average, MAX((SELECT COUNT(*) FROM jsonb_object_keys(attributes)))::text AS maximum FROM products`),
    queryNeon<RawAttributeRow>(`SELECT a.key, COUNT(*)::text AS products, (ARRAY_AGG(DISTINCT COALESCE(a.value->>'value', a.value #>> '{}')) FILTER (WHERE COALESCE(a.value->>'value', a.value #>> '{}') <> ''))[1:3] AS examples FROM products p CROSS JOIN LATERAL jsonb_each(CASE WHEN jsonb_typeof(p.attributes) = 'object' THEN p.attributes ELSE '{}'::jsonb END) a GROUP BY a.key ORDER BY COUNT(*) DESC, a.key LIMIT 120`),
    queryNeon<CanonicalAttributeRow>(`SELECT a.id, a.source_attribute_code, a.name, a.data_type, a.is_filterable, COUNT(DISTINCT pav.product_id)::text AS products FROM attributes a LEFT JOIN product_attribute_values pav ON pav.source_attribute_code = a.source_attribute_code GROUP BY a.id, a.source_attribute_code, a.name, a.data_type, a.is_filterable ORDER BY a.name LIMIT 500`),
  ]);
  const summary = stats[0];
  return <div className="mx-auto max-w-7xl space-y-6"><div><h2 className="text-2xl font-bold">Atribúty produktov</h2><p className="mt-1 text-sm text-slate-600">Kanonické atribúty a zdrojové technické parametre importované z eD.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Produkty', summary?.products], ['S atribútmi', summary?.with_attributes], ['Priemer atribútov', summary?.average], ['Maximum', summary?.maximum]].map(([label, value]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value || '0'}</p></div>)}</div><section className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-4"><h3 className="font-bold">Kanonický slovník</h3><p className="mt-1 text-xs text-slate-500">Tieto záznamy sú určené pre filtre, mapovania a kategóriové pravidlá.</p></div><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Názov</th><th className="px-4 py-3">Zdrojový kód</th><th className="px-4 py-3">Typ</th><th className="px-4 py-3">Filter</th><th className="px-4 py-3">Produktov</th></tr></thead><tbody className="divide-y divide-slate-100">{canonicalRows.map((row) => <tr key={row.id}><td className="px-4 py-3 font-semibold">{row.name}</td><td className="px-4 py-3 font-mono text-xs">{row.source_attribute_code || row.id}</td><td className="px-4 py-3">{row.data_type}</td><td className="px-4 py-3">{row.is_filterable ? 'Áno' : 'Nie'}</td><td className="px-4 py-3">{row.products}</td></tr>)}</tbody></table>{canonicalRows.length === 0 ? <p className="p-8 text-center text-slate-500">Kanonický slovník zatiaľ čaká na referenčný sync.</p> : null}</section><section className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-4"><h3 className="font-bold">Raw atribúty z produktov</h3></div><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Kľúč</th><th className="px-4 py-3">Produktov</th><th className="px-4 py-3">Príklady hodnôt</th></tr></thead><tbody className="divide-y divide-slate-100">{rawRows.map((row) => <tr key={row.key}><td className="px-4 py-3 font-mono text-xs">{row.key}</td><td className="px-4 py-3 font-semibold">{row.products}</td><td className="max-w-xl px-4 py-3 text-slate-600">{(row.examples || []).filter(Boolean).join(' · ')}</td></tr>)}</tbody></table></section></div>;
}
