import { redirect } from 'next/navigation';
import { isAdminAuthenticated } from '../auth';
import { updateOrderStatus } from '../actions';
import { queryNeon } from '../../../lib/neon-client';

export const dynamic = 'force-dynamic';

const statusLabels: Record<string, string> = { NEW: 'Nová', PROCESSING: 'Spracováva sa', SHIPPED: 'Odoslaná', COMPLETED: 'Dokončená', CANCELLED: 'Zrušená' };
const paymentLabels: Record<string, string> = { PENDING: 'Čaká na platbu', PAID: 'Zaplatená', FAILED: 'Neúspešná', REFUNDED: 'Vrátená' };

export default async function AdminOrders({ searchParams }: { searchParams: Promise<{ saved?: string }> }) {
  if (!(await isAdminAuthenticated())) redirect('/admin');
  const params = await searchParams;
  const orders = await queryNeon<{ id: string; order_number: string; customer_name: string; customer_email: string; customer_type: string; customer_ico: string | null; customer_dic: string | null; total: string; currency: string; status: string; payment_status: string; payment_method: string; created_at: string }>(`SELECT id, order_number, customer_name, customer_email, COALESCE(customer_type, 'PRIVATE') AS customer_type, customer_ico, customer_dic, total, currency, status, payment_status, payment_method, created_at FROM orders ORDER BY created_at DESC LIMIT 200`);
  return <div><h2 className="text-2xl font-bold">Objednávky</h2><p className="mt-1 text-sm text-slate-600">Prehľad objednávok a aktualizácia ich spracovania.</p>{params.saved ? <p className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">Objednávka bola aktualizovaná.</p> : null}<div className="mt-6 space-y-4">{orders.map((order) => <article key={order.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="font-bold">{order.order_number}</h3><p className="mt-1 text-sm text-slate-600">{order.customer_name} · {order.customer_email}</p><p className="text-xs text-slate-500">{order.customer_type === 'LEGAL' ? `Právnická osoba · IČO ${order.customer_ico || '—'} · DIČ ${order.customer_dic || '—'}` : 'Súkromná osoba'}</p></div><div className="text-right"><p className="text-lg font-black">{Number(order.total).toFixed(2)} {order.currency}</p><p className="text-xs text-slate-500">{new Date(order.created_at).toLocaleString('sk-SK')}</p></div></div><form action={updateOrderStatus} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="id" value={order.id} /><label className="text-xs font-semibold">Stav objednávky<select name="status" defaultValue={order.status} className="mt-1 block rounded-lg border p-2 text-sm">{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs font-semibold">Platba<select name="payment_status" defaultValue={order.payment_status} className="mt-1 block rounded-lg border p-2 text-sm">{Object.entries(paymentLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><span className="pb-2 text-xs text-slate-500">{order.payment_method === 'COD' ? 'Dobierka' : 'Bankový prevod'}</span><button className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Uložiť stav</button></form></article>)}{orders.length === 0 ? <p className="rounded-xl bg-white p-8 text-center text-slate-500">Zatiaľ neexistujú žiadne objednávky.</p> : null}</div></div>;
}
